<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Layout Handles</a></li>
		<li><a href="#tabs-2">Layout XML</a></li>		
	</ul>
	<div id="tabs-1"><?php pr(Mage::app()->getLayout()->getUpdate()->getHandles()); ?></div>
	<div id="tabs-2"><?php pr(htmlentities(Mage::app()->getLayout()->getUpdate()->asString())); ?></div>
</div>
<script type="text/javascript">
//$j(function() {
//	$j('#tabs').tabs();
//});
</script>
