<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
		
		<div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
		
        <div class="product-shop">
        	<table cellpadding="10" cellspacing="0" border="0" class="product-shop-table">
        		<tr class="title">
					<td class="label"><?php echo $this->__("Title:") ?></td>
					<td class="italic-title content"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></td>
					<td rowspan="10" class="additional" style="text-align:center;">
						<p class="printer-friendly"><?php echo $this->getChildHtml('addto');?></p>
						<p class="printer-friendly"><a href="<?php echo $this->helper('printerfriendly')->getPrintFriendlyUrl($_product) ?>" onclick="popWin('<?php echo $this->helper("printerfriendly")->getPrintFriendlyUrl($_product) ?>','compare','top:0,left:0,resizable=yes,scrollbars=yes'); return false; " ><?php echo $this->__('Printer Friendly Version') ?></a></p>
						<p class="printer-friendly"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
						<?php echo $this->getChildHtml('addtocart') ?>
						<?php echo $this->getChildHtml('product_type_data') ?>
					</td>
				</tr>
                <tr class="title">
					<td class="label"><?php echo $this->__("Publication Details:") ?></td>
					<td class="content"><?php echo $_helper->productAttribute($_product, $_product->getPublicationDetails() , 'entry_date'); ?></td>
				</tr>
				<tr>
					<td class="label"><?php echo $this->__("Stock Number:") ?></td>
					<td class="content"><?php echo $_product->getData('sku'); ?></td>
				</tr>
			</table>
			<table cellpadding="10" cellspacing="0" border="0" class="product-shop-table">		
				<tr>
					<td class="label"><?php echo $this->__("Description:") ?></td>
					<td class="content" colspan="2"><?php echo nl2br($_product->getData('description')); ?></td>
				</tr>
        	</table>
        </div>
        <div class="clearer"></div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>
</div>
